---
title: "Untitled"
author: "Justas Mundeikis"
date: "3/14/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=FALSE}
# paketai kurie reikalingi kodo veikimui
if(!require("magrittr")) install.packages("magrittr"); library("magrittr")
if(!require("lubridate")) install.packages("lubridate"); library("lubridate")
if(!require("tidyverse")) install.packages("tidyverse"); library("tidyverse")
if(!require("gridExtra")) install.packages("gridExtra"); library("gridExtra")
if(!require("kableExtra")) install.packages("kableExtra"); library("kableExtra")
if(!require("RColorBrewer")) install.packages("RColorBrewer"); library("RColorBrewer")
if(!require("scales")) install.packages("scales"); library("scales")
if(!require("rgdal")) install.packages("rgdal"); library("rgdal")
if(!require("sf")) install.packages("sf"); library("sf")
```

```{r, include=FALSE}
# duomenų importas
# duomenų šaltinis: Rhttps://github.com/CSSEGISandData/COVID-19
# 2019 Novel Coronavirus COVID-19 (2019-nCoV) Data Repository by Johns Hopkins CSSE     
data_confirmed <-read.csv('https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_19-covid-Confirmed.csv',
                          stringsAsFactors = FALSE)
data_deaths <-read.csv('https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_19-covid-Deaths.csv',
                       stringsAsFactors = FALSE)
data_recovered <-read.csv('https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_19-covid-Recovered.csv',
                          stringsAsFactors = FALSE)

```

```{r, include=FALSE}
# TODO:
# šalies pakeitimai prieš summary, arba reikia daryti ant pavienių datasetų po importo,
# arba pirma apjungti DS ir tada
# reikia papildomo žingsnio verifikavimui (vidiniam) ar  šalys iš  Hopkinso ir žemėlapių atitinka, nes atsiradus naujoms šalims reikės rankutėmis koreguot... hopkins naudoja WHO šlaių pavadinimus, žemėlapiai ne...

data$country[data$country=="Congo (Kinshasa)"] <- "Democratic Republic of the Congo"
data$country[data$country=="Cote d'Ivoire"] <- "Ivory Coast"
data$country[data$country=="French Guiana"] <- "France"
data$country[data$country=="Martinique"] <- "France"
data$country[data$country=="Reunion"] <- "France"
data$country[data$country=="Holy See"] <- "Vatican"
data$country[data$country=="Korea, South"] <- "South Korea"
data$country[data$country=="North Macedonia"] <- "Macedonia"
data$country[data$country=="Serbia"] <- "Republic of Serbia"
data$country[data$country=="US"] <- "United States of America"


```

```{r, include=FALSE}
# TODO:
# reikia importą zipo ir failo paėmimą iš zipo padaryt, nes dabar iš working directory ima

# INFO:
# https://www.naturalearthdata.com/downloads/50m-cultural-vectors/50m-admin-0-countries-2


countries <- readOGR(dsn ="./ne_50m_admin_0_sovereignty.shp", 
                             encoding = "utf-8",
                             use_iconv = T,
                             verbose = FALSE,
                     stringsAsFactors = FALSE)

countries <- st_as_sf(countries)


```

```{r, include=FALSE}


cleaning_data <- function(data) {
        data %<>% select(-c(Province.State, Lat, Long)) %>% rename(country=Country.Region)
        data %<>% gather(key=date, value=count, -country)
        data %<>% mutate(date=date %>%substr(2,8) %>% mdy())
        data %<>% group_by(country, date) %>% summarise(count=sum(count)) %>% as.data.frame()
}


```
# Įvadas
Lorre ipsum

```{r}
2+2
```

# Duomenys
```{r}
library(gsheet)
# Duomenys apie Corona atvejus iš spaudos pranešimų
corona_gs_sheet <- gsheet2tbl("https://docs.google.com/spreadsheets/d/1l9HM2hIjLFA-SZy_kO8b8B5Ddr0hfVZrmx2Yb1n1feg/edit#gid=0")

# Agreguojame atvejus vienos dienos lygmeniu
corona_gs_sheet %>% group_by(date, var) %>% summarize(value = sum(Value))
corona_gs_sheet %>% group_by(date, var, county_2) %>% summarize(value = sum(Value))

```

# Rezultatai
Lorre ipsum

# Pasaulinė statistika
Lorre ipsum

# Europos statistika
Lorre ipsum

# Lietuvos statistika
Lorre ipsum

